// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

type CreateUserParams struct {
    Firstname string
    Lastname  string
    Gender    string
    StudentId string
    Course    string
    Level     string
    Email     string
}
