// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users.sql

package database

import (
	"context"
)

const createUser = `-- name: CreateUser :one
CREATE TABLE register (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Firstname VARCHAR(255) NOT NULL,
    Lastname VARCHAR(255) NOT NULL,
    Gender VARCHAR(10) NOT NULL,
    StudentId VARCHAR(50) NOT NULL,
    Course VARCHAR(255) NOT NULL,
    Level VARCHAR(50) NOT NULL,
    Email VARCHAR(255) NOT NULL
)
`

type CreateUserRow struct {
}
func (q *Queries) CreateUser(ctx context.Context, args CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRowContext(ctx, createUser)
	var i CreateUserRow
	err := row.Scan()
	return i, err
}
